/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard/projects/index'
import { Route as DashboardProjectsProject_idIndexRouteImport } from './routes/_dashboard/projects/$project_id/index'
import { Route as DashboardProjectsProject_idSdkRouteImport } from './routes/_dashboard/projects/$project_id/sdk'
import { Route as DashboardProjectsProject_idIntegrationsRouteImport } from './routes/_dashboard/projects/$project_id/integrations'
import { Route as DashboardProjectsProject_idChecklistsRouteImport } from './routes/_dashboard/projects/$project_id/checklists'
import { Route as DashboardProjectsProject_idReleasesNewRouteImport } from './routes/_dashboard/projects/$project_id/releases/new'
import { Route as DashboardProjectsProject_idReleasesRelease_idRouteImport } from './routes/_dashboard/projects/$project_id/releases/$release_id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsProject_idIndexRoute =
  DashboardProjectsProject_idIndexRouteImport.update({
    id: '/projects/$project_id/',
    path: '/projects/$project_id/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsProject_idSdkRoute =
  DashboardProjectsProject_idSdkRouteImport.update({
    id: '/projects/$project_id/sdk',
    path: '/projects/$project_id/sdk',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsProject_idIntegrationsRoute =
  DashboardProjectsProject_idIntegrationsRouteImport.update({
    id: '/projects/$project_id/integrations',
    path: '/projects/$project_id/integrations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsProject_idChecklistsRoute =
  DashboardProjectsProject_idChecklistsRouteImport.update({
    id: '/projects/$project_id/checklists',
    path: '/projects/$project_id/checklists',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsProject_idReleasesNewRoute =
  DashboardProjectsProject_idReleasesNewRouteImport.update({
    id: '/projects/$project_id/releases/new',
    path: '/projects/$project_id/releases/new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsProject_idReleasesRelease_idRoute =
  DashboardProjectsProject_idReleasesRelease_idRouteImport.update({
    id: '/projects/$project_id/releases/$release_id',
    path: '/projects/$project_id/releases/$release_id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/': typeof DashboardProjectsIndexRoute
  '/projects/$project_id/checklists': typeof DashboardProjectsProject_idChecklistsRoute
  '/projects/$project_id/integrations': typeof DashboardProjectsProject_idIntegrationsRoute
  '/projects/$project_id/sdk': typeof DashboardProjectsProject_idSdkRoute
  '/projects/$project_id/': typeof DashboardProjectsProject_idIndexRoute
  '/projects/$project_id/releases/$release_id': typeof DashboardProjectsProject_idReleasesRelease_idRoute
  '/projects/$project_id/releases/new': typeof DashboardProjectsProject_idReleasesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/projects/$project_id/checklists': typeof DashboardProjectsProject_idChecklistsRoute
  '/projects/$project_id/integrations': typeof DashboardProjectsProject_idIntegrationsRoute
  '/projects/$project_id/sdk': typeof DashboardProjectsProject_idSdkRoute
  '/projects/$project_id': typeof DashboardProjectsProject_idIndexRoute
  '/projects/$project_id/releases/$release_id': typeof DashboardProjectsProject_idReleasesRelease_idRoute
  '/projects/$project_id/releases/new': typeof DashboardProjectsProject_idReleasesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/projects/$project_id/checklists': typeof DashboardProjectsProject_idChecklistsRoute
  '/_dashboard/projects/$project_id/integrations': typeof DashboardProjectsProject_idIntegrationsRoute
  '/_dashboard/projects/$project_id/sdk': typeof DashboardProjectsProject_idSdkRoute
  '/_dashboard/projects/$project_id/': typeof DashboardProjectsProject_idIndexRoute
  '/_dashboard/projects/$project_id/releases/$release_id': typeof DashboardProjectsProject_idReleasesRelease_idRoute
  '/_dashboard/projects/$project_id/releases/new': typeof DashboardProjectsProject_idReleasesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/projects/'
    | '/projects/$project_id/checklists'
    | '/projects/$project_id/integrations'
    | '/projects/$project_id/sdk'
    | '/projects/$project_id/'
    | '/projects/$project_id/releases/$release_id'
    | '/projects/$project_id/releases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/projects'
    | '/projects/$project_id/checklists'
    | '/projects/$project_id/integrations'
    | '/projects/$project_id/sdk'
    | '/projects/$project_id'
    | '/projects/$project_id/releases/$release_id'
    | '/projects/$project_id/releases/new'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/register'
    | '/_dashboard/projects/'
    | '/_dashboard/projects/$project_id/checklists'
    | '/_dashboard/projects/$project_id/integrations'
    | '/_dashboard/projects/$project_id/sdk'
    | '/_dashboard/projects/$project_id/'
    | '/_dashboard/projects/$project_id/releases/$release_id'
    | '/_dashboard/projects/$project_id/releases/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/projects/$project_id/': {
      id: '/_dashboard/projects/$project_id/'
      path: '/projects/$project_id'
      fullPath: '/projects/$project_id/'
      preLoaderRoute: typeof DashboardProjectsProject_idIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/projects/$project_id/sdk': {
      id: '/_dashboard/projects/$project_id/sdk'
      path: '/projects/$project_id/sdk'
      fullPath: '/projects/$project_id/sdk'
      preLoaderRoute: typeof DashboardProjectsProject_idSdkRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/projects/$project_id/integrations': {
      id: '/_dashboard/projects/$project_id/integrations'
      path: '/projects/$project_id/integrations'
      fullPath: '/projects/$project_id/integrations'
      preLoaderRoute: typeof DashboardProjectsProject_idIntegrationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/projects/$project_id/checklists': {
      id: '/_dashboard/projects/$project_id/checklists'
      path: '/projects/$project_id/checklists'
      fullPath: '/projects/$project_id/checklists'
      preLoaderRoute: typeof DashboardProjectsProject_idChecklistsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/projects/$project_id/releases/new': {
      id: '/_dashboard/projects/$project_id/releases/new'
      path: '/projects/$project_id/releases/new'
      fullPath: '/projects/$project_id/releases/new'
      preLoaderRoute: typeof DashboardProjectsProject_idReleasesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/projects/$project_id/releases/$release_id': {
      id: '/_dashboard/projects/$project_id/releases/$release_id'
      path: '/projects/$project_id/releases/$release_id'
      fullPath: '/projects/$project_id/releases/$release_id'
      preLoaderRoute: typeof DashboardProjectsProject_idReleasesRelease_idRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardProjectsProject_idChecklistsRoute: typeof DashboardProjectsProject_idChecklistsRoute
  DashboardProjectsProject_idIntegrationsRoute: typeof DashboardProjectsProject_idIntegrationsRoute
  DashboardProjectsProject_idSdkRoute: typeof DashboardProjectsProject_idSdkRoute
  DashboardProjectsProject_idIndexRoute: typeof DashboardProjectsProject_idIndexRoute
  DashboardProjectsProject_idReleasesRelease_idRoute: typeof DashboardProjectsProject_idReleasesRelease_idRoute
  DashboardProjectsProject_idReleasesNewRoute: typeof DashboardProjectsProject_idReleasesNewRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardProjectsProject_idChecklistsRoute:
    DashboardProjectsProject_idChecklistsRoute,
  DashboardProjectsProject_idIntegrationsRoute:
    DashboardProjectsProject_idIntegrationsRoute,
  DashboardProjectsProject_idSdkRoute: DashboardProjectsProject_idSdkRoute,
  DashboardProjectsProject_idIndexRoute: DashboardProjectsProject_idIndexRoute,
  DashboardProjectsProject_idReleasesRelease_idRoute:
    DashboardProjectsProject_idReleasesRelease_idRoute,
  DashboardProjectsProject_idReleasesNewRoute:
    DashboardProjectsProject_idReleasesNewRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
