/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTasksRouteImport } from './routes/_dashboard/tasks'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard/home'
import { Route as DashboardEmailsRouteImport } from './routes/_dashboard/emails'
import { Route as DashboardPeopleIndexRouteImport } from './routes/_dashboard/people/index'
import { Route as DashboardCompaniesIndexRouteImport } from './routes/_dashboard/companies/index'
import { Route as DashboardPeoplePersonIdRouteImport } from './routes/_dashboard/people/$personId'
import { Route as DashboardCompaniesCompanyIdRouteImport } from './routes/_dashboard/companies/$companyId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailsRoute = DashboardEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPeopleIndexRoute = DashboardPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCompaniesIndexRoute = DashboardCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPeoplePersonIdRoute = DashboardPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCompaniesCompanyIdRoute =
  DashboardCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/emails': typeof DashboardEmailsRoute
  '/home': typeof DashboardHomeRoute
  '/settings': typeof DashboardSettingsRoute
  '/tasks': typeof DashboardTasksRoute
  '/companies/$companyId': typeof DashboardCompaniesCompanyIdRoute
  '/people/$personId': typeof DashboardPeoplePersonIdRoute
  '/companies/': typeof DashboardCompaniesIndexRoute
  '/people/': typeof DashboardPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/emails': typeof DashboardEmailsRoute
  '/home': typeof DashboardHomeRoute
  '/settings': typeof DashboardSettingsRoute
  '/tasks': typeof DashboardTasksRoute
  '/companies/$companyId': typeof DashboardCompaniesCompanyIdRoute
  '/people/$personId': typeof DashboardPeoplePersonIdRoute
  '/companies': typeof DashboardCompaniesIndexRoute
  '/people': typeof DashboardPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/emails': typeof DashboardEmailsRoute
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/tasks': typeof DashboardTasksRoute
  '/_dashboard/companies/$companyId': typeof DashboardCompaniesCompanyIdRoute
  '/_dashboard/people/$personId': typeof DashboardPeoplePersonIdRoute
  '/_dashboard/companies/': typeof DashboardCompaniesIndexRoute
  '/_dashboard/people/': typeof DashboardPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/emails'
    | '/home'
    | '/settings'
    | '/tasks'
    | '/companies/$companyId'
    | '/people/$personId'
    | '/companies/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/emails'
    | '/home'
    | '/settings'
    | '/tasks'
    | '/companies/$companyId'
    | '/people/$personId'
    | '/companies'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/emails'
    | '/_dashboard/home'
    | '/_dashboard/settings'
    | '/_dashboard/tasks'
    | '/_dashboard/companies/$companyId'
    | '/_dashboard/people/$personId'
    | '/_dashboard/companies/'
    | '/_dashboard/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/tasks': {
      id: '/_dashboard/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/emails': {
      id: '/_dashboard/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof DashboardEmailsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/people/': {
      id: '/_dashboard/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof DashboardPeopleIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/companies/': {
      id: '/_dashboard/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof DashboardCompaniesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/people/$personId': {
      id: '/_dashboard/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof DashboardPeoplePersonIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/companies/$companyId': {
      id: '/_dashboard/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof DashboardCompaniesCompanyIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardEmailsRoute: typeof DashboardEmailsRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardCompaniesCompanyIdRoute: typeof DashboardCompaniesCompanyIdRoute
  DashboardPeoplePersonIdRoute: typeof DashboardPeoplePersonIdRoute
  DashboardCompaniesIndexRoute: typeof DashboardCompaniesIndexRoute
  DashboardPeopleIndexRoute: typeof DashboardPeopleIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardEmailsRoute: DashboardEmailsRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardCompaniesCompanyIdRoute: DashboardCompaniesCompanyIdRoute,
  DashboardPeoplePersonIdRoute: DashboardPeoplePersonIdRoute,
  DashboardCompaniesIndexRoute: DashboardCompaniesIndexRoute,
  DashboardPeopleIndexRoute: DashboardPeopleIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
