/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as DashboardMailboxIdRouteRouteImport } from './routes/_dashboard/$mailboxId/route'
import { Route as DashboardMailboxIdIndexRouteImport } from './routes/_dashboard/$mailboxId/index'
import { Route as EmailMailboxIdEmailIdRouteImport } from './routes/email/$mailboxId/$emailId'
import { Route as DashboardMailboxIdSubscriptionsRouteImport } from './routes/_dashboard/$mailboxId/subscriptions'
import { Route as DashboardMailboxIdScreenerRouteImport } from './routes/_dashboard/$mailboxId/screener'
import { Route as DashboardMailboxIdSettingsRouteRouteImport } from './routes/_dashboard/$mailboxId/settings/route'
import { Route as DashboardMailboxIdSettingsIndexRouteImport } from './routes/_dashboard/$mailboxId/settings/index'
import { Route as DashboardMailboxIdInboxIndexRouteImport } from './routes/_dashboard/$mailboxId/inbox/index'
import { Route as DashboardMailboxIdFolderIndexRouteImport } from './routes/_dashboard/$mailboxId/$folder/index'
import { Route as DashboardMailboxIdSettingsTemplatesRouteImport } from './routes/_dashboard/$mailboxId/settings/templates'
import { Route as DashboardMailboxIdSettingsSignaturesRouteImport } from './routes/_dashboard/$mailboxId/settings/signatures'
import { Route as DashboardMailboxIdSettingsPerformanceRouteImport } from './routes/_dashboard/$mailboxId/settings/performance'
import { Route as DashboardMailboxIdSettingsMailboxRouteImport } from './routes/_dashboard/$mailboxId/settings/mailbox'
import { Route as DashboardMailboxIdSettingsLabelsRouteImport } from './routes/_dashboard/$mailboxId/settings/labels'
import { Route as DashboardMailboxIdSettingsDangerRouteImport } from './routes/_dashboard/$mailboxId/settings/danger'
import { Route as DashboardMailboxIdSettingsAppearanceRouteImport } from './routes/_dashboard/$mailboxId/settings/appearance'
import { Route as DashboardMailboxIdSettingsAiRouteImport } from './routes/_dashboard/$mailboxId/settings/ai'
import { Route as DashboardMailboxIdSettingsAccountRouteImport } from './routes/_dashboard/$mailboxId/settings/account'
import { Route as DashboardMailboxIdInboxSearchRouteImport } from './routes/_dashboard/$mailboxId/inbox/search'
import { Route as DashboardMailboxIdInboxDraftsRouteImport } from './routes/_dashboard/$mailboxId/inbox/drafts'
import { Route as DashboardMailboxIdViewsViewIdIndexRouteImport } from './routes/_dashboard/$mailboxId/views/$viewId/index'
import { Route as DashboardMailboxIdInboxEmailEmailIdRouteImport } from './routes/_dashboard/$mailboxId/inbox/email/$emailId'
import { Route as DashboardMailboxIdFolderEmailEmailIdRouteImport } from './routes/_dashboard/$mailboxId/$folder/email/$emailId'
import { Route as DashboardMailboxIdInboxLabelsLabelIndexRouteImport } from './routes/_dashboard/$mailboxId/inbox/labels/$label/index'
import { Route as DashboardMailboxIdInboxLabelsLabelEmailEmailIdRouteImport } from './routes/_dashboard/$mailboxId/inbox/labels/$label/email/$emailId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DashboardMailboxIdRouteRoute = DashboardMailboxIdRouteRouteImport.update({
  id: '/$mailboxId',
  path: '/$mailboxId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMailboxIdIndexRoute = DashboardMailboxIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMailboxIdRouteRoute,
} as any)
const EmailMailboxIdEmailIdRoute = EmailMailboxIdEmailIdRouteImport.update({
  id: '/email/$mailboxId/$emailId',
  path: '/email/$mailboxId/$emailId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMailboxIdSubscriptionsRoute =
  DashboardMailboxIdSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdScreenerRoute =
  DashboardMailboxIdScreenerRouteImport.update({
    id: '/screener',
    path: '/screener',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdSettingsRouteRoute =
  DashboardMailboxIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdSettingsIndexRoute =
  DashboardMailboxIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdInboxIndexRoute =
  DashboardMailboxIdInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdFolderIndexRoute =
  DashboardMailboxIdFolderIndexRouteImport.update({
    id: '/$folder/',
    path: '/$folder/',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdSettingsTemplatesRoute =
  DashboardMailboxIdSettingsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdSettingsSignaturesRoute =
  DashboardMailboxIdSettingsSignaturesRouteImport.update({
    id: '/signatures',
    path: '/signatures',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdSettingsPerformanceRoute =
  DashboardMailboxIdSettingsPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdSettingsMailboxRoute =
  DashboardMailboxIdSettingsMailboxRouteImport.update({
    id: '/mailbox',
    path: '/mailbox',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdSettingsLabelsRoute =
  DashboardMailboxIdSettingsLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdSettingsDangerRoute =
  DashboardMailboxIdSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdSettingsAppearanceRoute =
  DashboardMailboxIdSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdSettingsAiRoute =
  DashboardMailboxIdSettingsAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdSettingsAccountRoute =
  DashboardMailboxIdSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardMailboxIdSettingsRouteRoute,
  } as any)
const DashboardMailboxIdInboxSearchRoute =
  DashboardMailboxIdInboxSearchRouteImport.update({
    id: '/inbox/search',
    path: '/inbox/search',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdInboxDraftsRoute =
  DashboardMailboxIdInboxDraftsRouteImport.update({
    id: '/inbox/drafts',
    path: '/inbox/drafts',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdViewsViewIdIndexRoute =
  DashboardMailboxIdViewsViewIdIndexRouteImport.update({
    id: '/views/$viewId/',
    path: '/views/$viewId/',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdInboxEmailEmailIdRoute =
  DashboardMailboxIdInboxEmailEmailIdRouteImport.update({
    id: '/inbox/email/$emailId',
    path: '/inbox/email/$emailId',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdFolderEmailEmailIdRoute =
  DashboardMailboxIdFolderEmailEmailIdRouteImport.update({
    id: '/$folder/email/$emailId',
    path: '/$folder/email/$emailId',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdInboxLabelsLabelIndexRoute =
  DashboardMailboxIdInboxLabelsLabelIndexRouteImport.update({
    id: '/inbox/labels/$label/',
    path: '/inbox/labels/$label/',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)
const DashboardMailboxIdInboxLabelsLabelEmailEmailIdRoute =
  DashboardMailboxIdInboxLabelsLabelEmailEmailIdRouteImport.update({
    id: '/inbox/labels/$label/email/$emailId',
    path: '/inbox/labels/$label/email/$emailId',
    getParentRoute: () => DashboardMailboxIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$mailboxId': typeof DashboardMailboxIdRouteRouteWithChildren
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/$mailboxId/settings': typeof DashboardMailboxIdSettingsRouteRouteWithChildren
  '/$mailboxId/screener': typeof DashboardMailboxIdScreenerRoute
  '/$mailboxId/subscriptions': typeof DashboardMailboxIdSubscriptionsRoute
  '/email/$mailboxId/$emailId': typeof EmailMailboxIdEmailIdRoute
  '/$mailboxId/': typeof DashboardMailboxIdIndexRoute
  '/$mailboxId/inbox/drafts': typeof DashboardMailboxIdInboxDraftsRoute
  '/$mailboxId/inbox/search': typeof DashboardMailboxIdInboxSearchRoute
  '/$mailboxId/settings/account': typeof DashboardMailboxIdSettingsAccountRoute
  '/$mailboxId/settings/ai': typeof DashboardMailboxIdSettingsAiRoute
  '/$mailboxId/settings/appearance': typeof DashboardMailboxIdSettingsAppearanceRoute
  '/$mailboxId/settings/danger': typeof DashboardMailboxIdSettingsDangerRoute
  '/$mailboxId/settings/labels': typeof DashboardMailboxIdSettingsLabelsRoute
  '/$mailboxId/settings/mailbox': typeof DashboardMailboxIdSettingsMailboxRoute
  '/$mailboxId/settings/performance': typeof DashboardMailboxIdSettingsPerformanceRoute
  '/$mailboxId/settings/signatures': typeof DashboardMailboxIdSettingsSignaturesRoute
  '/$mailboxId/settings/templates': typeof DashboardMailboxIdSettingsTemplatesRoute
  '/$mailboxId/$folder/': typeof DashboardMailboxIdFolderIndexRoute
  '/$mailboxId/inbox/': typeof DashboardMailboxIdInboxIndexRoute
  '/$mailboxId/settings/': typeof DashboardMailboxIdSettingsIndexRoute
  '/$mailboxId/$folder/email/$emailId': typeof DashboardMailboxIdFolderEmailEmailIdRoute
  '/$mailboxId/inbox/email/$emailId': typeof DashboardMailboxIdInboxEmailEmailIdRoute
  '/$mailboxId/views/$viewId/': typeof DashboardMailboxIdViewsViewIdIndexRoute
  '/$mailboxId/inbox/labels/$label/': typeof DashboardMailboxIdInboxLabelsLabelIndexRoute
  '/$mailboxId/inbox/labels/$label/email/$emailId': typeof DashboardMailboxIdInboxLabelsLabelEmailEmailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs': typeof DocsIndexRoute
  '/$mailboxId/screener': typeof DashboardMailboxIdScreenerRoute
  '/$mailboxId/subscriptions': typeof DashboardMailboxIdSubscriptionsRoute
  '/email/$mailboxId/$emailId': typeof EmailMailboxIdEmailIdRoute
  '/$mailboxId': typeof DashboardMailboxIdIndexRoute
  '/$mailboxId/inbox/drafts': typeof DashboardMailboxIdInboxDraftsRoute
  '/$mailboxId/inbox/search': typeof DashboardMailboxIdInboxSearchRoute
  '/$mailboxId/settings/account': typeof DashboardMailboxIdSettingsAccountRoute
  '/$mailboxId/settings/ai': typeof DashboardMailboxIdSettingsAiRoute
  '/$mailboxId/settings/appearance': typeof DashboardMailboxIdSettingsAppearanceRoute
  '/$mailboxId/settings/danger': typeof DashboardMailboxIdSettingsDangerRoute
  '/$mailboxId/settings/labels': typeof DashboardMailboxIdSettingsLabelsRoute
  '/$mailboxId/settings/mailbox': typeof DashboardMailboxIdSettingsMailboxRoute
  '/$mailboxId/settings/performance': typeof DashboardMailboxIdSettingsPerformanceRoute
  '/$mailboxId/settings/signatures': typeof DashboardMailboxIdSettingsSignaturesRoute
  '/$mailboxId/settings/templates': typeof DashboardMailboxIdSettingsTemplatesRoute
  '/$mailboxId/$folder': typeof DashboardMailboxIdFolderIndexRoute
  '/$mailboxId/inbox': typeof DashboardMailboxIdInboxIndexRoute
  '/$mailboxId/settings': typeof DashboardMailboxIdSettingsIndexRoute
  '/$mailboxId/$folder/email/$emailId': typeof DashboardMailboxIdFolderEmailEmailIdRoute
  '/$mailboxId/inbox/email/$emailId': typeof DashboardMailboxIdInboxEmailEmailIdRoute
  '/$mailboxId/views/$viewId': typeof DashboardMailboxIdViewsViewIdIndexRoute
  '/$mailboxId/inbox/labels/$label': typeof DashboardMailboxIdInboxLabelsLabelIndexRoute
  '/$mailboxId/inbox/labels/$label/email/$emailId': typeof DashboardMailboxIdInboxLabelsLabelEmailEmailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_dashboard/$mailboxId': typeof DashboardMailboxIdRouteRouteWithChildren
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/_dashboard/$mailboxId/settings': typeof DashboardMailboxIdSettingsRouteRouteWithChildren
  '/_dashboard/$mailboxId/screener': typeof DashboardMailboxIdScreenerRoute
  '/_dashboard/$mailboxId/subscriptions': typeof DashboardMailboxIdSubscriptionsRoute
  '/email/$mailboxId/$emailId': typeof EmailMailboxIdEmailIdRoute
  '/_dashboard/$mailboxId/': typeof DashboardMailboxIdIndexRoute
  '/_dashboard/$mailboxId/inbox/drafts': typeof DashboardMailboxIdInboxDraftsRoute
  '/_dashboard/$mailboxId/inbox/search': typeof DashboardMailboxIdInboxSearchRoute
  '/_dashboard/$mailboxId/settings/account': typeof DashboardMailboxIdSettingsAccountRoute
  '/_dashboard/$mailboxId/settings/ai': typeof DashboardMailboxIdSettingsAiRoute
  '/_dashboard/$mailboxId/settings/appearance': typeof DashboardMailboxIdSettingsAppearanceRoute
  '/_dashboard/$mailboxId/settings/danger': typeof DashboardMailboxIdSettingsDangerRoute
  '/_dashboard/$mailboxId/settings/labels': typeof DashboardMailboxIdSettingsLabelsRoute
  '/_dashboard/$mailboxId/settings/mailbox': typeof DashboardMailboxIdSettingsMailboxRoute
  '/_dashboard/$mailboxId/settings/performance': typeof DashboardMailboxIdSettingsPerformanceRoute
  '/_dashboard/$mailboxId/settings/signatures': typeof DashboardMailboxIdSettingsSignaturesRoute
  '/_dashboard/$mailboxId/settings/templates': typeof DashboardMailboxIdSettingsTemplatesRoute
  '/_dashboard/$mailboxId/$folder/': typeof DashboardMailboxIdFolderIndexRoute
  '/_dashboard/$mailboxId/inbox/': typeof DashboardMailboxIdInboxIndexRoute
  '/_dashboard/$mailboxId/settings/': typeof DashboardMailboxIdSettingsIndexRoute
  '/_dashboard/$mailboxId/$folder/email/$emailId': typeof DashboardMailboxIdFolderEmailEmailIdRoute
  '/_dashboard/$mailboxId/inbox/email/$emailId': typeof DashboardMailboxIdInboxEmailEmailIdRoute
  '/_dashboard/$mailboxId/views/$viewId/': typeof DashboardMailboxIdViewsViewIdIndexRoute
  '/_dashboard/$mailboxId/inbox/labels/$label/': typeof DashboardMailboxIdInboxLabelsLabelIndexRoute
  '/_dashboard/$mailboxId/inbox/labels/$label/email/$emailId': typeof DashboardMailboxIdInboxLabelsLabelEmailEmailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/$mailboxId'
    | '/docs/$slug'
    | '/docs/'
    | '/$mailboxId/settings'
    | '/$mailboxId/screener'
    | '/$mailboxId/subscriptions'
    | '/email/$mailboxId/$emailId'
    | '/$mailboxId/'
    | '/$mailboxId/inbox/drafts'
    | '/$mailboxId/inbox/search'
    | '/$mailboxId/settings/account'
    | '/$mailboxId/settings/ai'
    | '/$mailboxId/settings/appearance'
    | '/$mailboxId/settings/danger'
    | '/$mailboxId/settings/labels'
    | '/$mailboxId/settings/mailbox'
    | '/$mailboxId/settings/performance'
    | '/$mailboxId/settings/signatures'
    | '/$mailboxId/settings/templates'
    | '/$mailboxId/$folder/'
    | '/$mailboxId/inbox/'
    | '/$mailboxId/settings/'
    | '/$mailboxId/$folder/email/$emailId'
    | '/$mailboxId/inbox/email/$emailId'
    | '/$mailboxId/views/$viewId/'
    | '/$mailboxId/inbox/labels/$label/'
    | '/$mailboxId/inbox/labels/$label/email/$emailId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/docs/$slug'
    | '/docs'
    | '/$mailboxId/screener'
    | '/$mailboxId/subscriptions'
    | '/email/$mailboxId/$emailId'
    | '/$mailboxId'
    | '/$mailboxId/inbox/drafts'
    | '/$mailboxId/inbox/search'
    | '/$mailboxId/settings/account'
    | '/$mailboxId/settings/ai'
    | '/$mailboxId/settings/appearance'
    | '/$mailboxId/settings/danger'
    | '/$mailboxId/settings/labels'
    | '/$mailboxId/settings/mailbox'
    | '/$mailboxId/settings/performance'
    | '/$mailboxId/settings/signatures'
    | '/$mailboxId/settings/templates'
    | '/$mailboxId/$folder'
    | '/$mailboxId/inbox'
    | '/$mailboxId/settings'
    | '/$mailboxId/$folder/email/$emailId'
    | '/$mailboxId/inbox/email/$emailId'
    | '/$mailboxId/views/$viewId'
    | '/$mailboxId/inbox/labels/$label'
    | '/$mailboxId/inbox/labels/$label/email/$emailId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/docs'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_dashboard/$mailboxId'
    | '/docs/$slug'
    | '/docs/'
    | '/_dashboard/$mailboxId/settings'
    | '/_dashboard/$mailboxId/screener'
    | '/_dashboard/$mailboxId/subscriptions'
    | '/email/$mailboxId/$emailId'
    | '/_dashboard/$mailboxId/'
    | '/_dashboard/$mailboxId/inbox/drafts'
    | '/_dashboard/$mailboxId/inbox/search'
    | '/_dashboard/$mailboxId/settings/account'
    | '/_dashboard/$mailboxId/settings/ai'
    | '/_dashboard/$mailboxId/settings/appearance'
    | '/_dashboard/$mailboxId/settings/danger'
    | '/_dashboard/$mailboxId/settings/labels'
    | '/_dashboard/$mailboxId/settings/mailbox'
    | '/_dashboard/$mailboxId/settings/performance'
    | '/_dashboard/$mailboxId/settings/signatures'
    | '/_dashboard/$mailboxId/settings/templates'
    | '/_dashboard/$mailboxId/$folder/'
    | '/_dashboard/$mailboxId/inbox/'
    | '/_dashboard/$mailboxId/settings/'
    | '/_dashboard/$mailboxId/$folder/email/$emailId'
    | '/_dashboard/$mailboxId/inbox/email/$emailId'
    | '/_dashboard/$mailboxId/views/$viewId/'
    | '/_dashboard/$mailboxId/inbox/labels/$label/'
    | '/_dashboard/$mailboxId/inbox/labels/$label/email/$emailId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EmailMailboxIdEmailIdRoute: typeof EmailMailboxIdEmailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_dashboard/$mailboxId': {
      id: '/_dashboard/$mailboxId'
      path: '/$mailboxId'
      fullPath: '/$mailboxId'
      preLoaderRoute: typeof DashboardMailboxIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/$mailboxId/': {
      id: '/_dashboard/$mailboxId/'
      path: '/'
      fullPath: '/$mailboxId/'
      preLoaderRoute: typeof DashboardMailboxIdIndexRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/email/$mailboxId/$emailId': {
      id: '/email/$mailboxId/$emailId'
      path: '/email/$mailboxId/$emailId'
      fullPath: '/email/$mailboxId/$emailId'
      preLoaderRoute: typeof EmailMailboxIdEmailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$mailboxId/subscriptions': {
      id: '/_dashboard/$mailboxId/subscriptions'
      path: '/subscriptions'
      fullPath: '/$mailboxId/subscriptions'
      preLoaderRoute: typeof DashboardMailboxIdSubscriptionsRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/screener': {
      id: '/_dashboard/$mailboxId/screener'
      path: '/screener'
      fullPath: '/$mailboxId/screener'
      preLoaderRoute: typeof DashboardMailboxIdScreenerRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/settings': {
      id: '/_dashboard/$mailboxId/settings'
      path: '/settings'
      fullPath: '/$mailboxId/settings'
      preLoaderRoute: typeof DashboardMailboxIdSettingsRouteRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/settings/': {
      id: '/_dashboard/$mailboxId/settings/'
      path: '/'
      fullPath: '/$mailboxId/settings/'
      preLoaderRoute: typeof DashboardMailboxIdSettingsIndexRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/inbox/': {
      id: '/_dashboard/$mailboxId/inbox/'
      path: '/inbox'
      fullPath: '/$mailboxId/inbox/'
      preLoaderRoute: typeof DashboardMailboxIdInboxIndexRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/$folder/': {
      id: '/_dashboard/$mailboxId/$folder/'
      path: '/$folder'
      fullPath: '/$mailboxId/$folder/'
      preLoaderRoute: typeof DashboardMailboxIdFolderIndexRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/settings/templates': {
      id: '/_dashboard/$mailboxId/settings/templates'
      path: '/templates'
      fullPath: '/$mailboxId/settings/templates'
      preLoaderRoute: typeof DashboardMailboxIdSettingsTemplatesRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/settings/signatures': {
      id: '/_dashboard/$mailboxId/settings/signatures'
      path: '/signatures'
      fullPath: '/$mailboxId/settings/signatures'
      preLoaderRoute: typeof DashboardMailboxIdSettingsSignaturesRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/settings/performance': {
      id: '/_dashboard/$mailboxId/settings/performance'
      path: '/performance'
      fullPath: '/$mailboxId/settings/performance'
      preLoaderRoute: typeof DashboardMailboxIdSettingsPerformanceRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/settings/mailbox': {
      id: '/_dashboard/$mailboxId/settings/mailbox'
      path: '/mailbox'
      fullPath: '/$mailboxId/settings/mailbox'
      preLoaderRoute: typeof DashboardMailboxIdSettingsMailboxRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/settings/labels': {
      id: '/_dashboard/$mailboxId/settings/labels'
      path: '/labels'
      fullPath: '/$mailboxId/settings/labels'
      preLoaderRoute: typeof DashboardMailboxIdSettingsLabelsRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/settings/danger': {
      id: '/_dashboard/$mailboxId/settings/danger'
      path: '/danger'
      fullPath: '/$mailboxId/settings/danger'
      preLoaderRoute: typeof DashboardMailboxIdSettingsDangerRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/settings/appearance': {
      id: '/_dashboard/$mailboxId/settings/appearance'
      path: '/appearance'
      fullPath: '/$mailboxId/settings/appearance'
      preLoaderRoute: typeof DashboardMailboxIdSettingsAppearanceRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/settings/ai': {
      id: '/_dashboard/$mailboxId/settings/ai'
      path: '/ai'
      fullPath: '/$mailboxId/settings/ai'
      preLoaderRoute: typeof DashboardMailboxIdSettingsAiRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/settings/account': {
      id: '/_dashboard/$mailboxId/settings/account'
      path: '/account'
      fullPath: '/$mailboxId/settings/account'
      preLoaderRoute: typeof DashboardMailboxIdSettingsAccountRouteImport
      parentRoute: typeof DashboardMailboxIdSettingsRouteRoute
    }
    '/_dashboard/$mailboxId/inbox/search': {
      id: '/_dashboard/$mailboxId/inbox/search'
      path: '/inbox/search'
      fullPath: '/$mailboxId/inbox/search'
      preLoaderRoute: typeof DashboardMailboxIdInboxSearchRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/inbox/drafts': {
      id: '/_dashboard/$mailboxId/inbox/drafts'
      path: '/inbox/drafts'
      fullPath: '/$mailboxId/inbox/drafts'
      preLoaderRoute: typeof DashboardMailboxIdInboxDraftsRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/views/$viewId/': {
      id: '/_dashboard/$mailboxId/views/$viewId/'
      path: '/views/$viewId'
      fullPath: '/$mailboxId/views/$viewId/'
      preLoaderRoute: typeof DashboardMailboxIdViewsViewIdIndexRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/inbox/email/$emailId': {
      id: '/_dashboard/$mailboxId/inbox/email/$emailId'
      path: '/inbox/email/$emailId'
      fullPath: '/$mailboxId/inbox/email/$emailId'
      preLoaderRoute: typeof DashboardMailboxIdInboxEmailEmailIdRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/$folder/email/$emailId': {
      id: '/_dashboard/$mailboxId/$folder/email/$emailId'
      path: '/$folder/email/$emailId'
      fullPath: '/$mailboxId/$folder/email/$emailId'
      preLoaderRoute: typeof DashboardMailboxIdFolderEmailEmailIdRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/inbox/labels/$label/': {
      id: '/_dashboard/$mailboxId/inbox/labels/$label/'
      path: '/inbox/labels/$label'
      fullPath: '/$mailboxId/inbox/labels/$label/'
      preLoaderRoute: typeof DashboardMailboxIdInboxLabelsLabelIndexRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
    '/_dashboard/$mailboxId/inbox/labels/$label/email/$emailId': {
      id: '/_dashboard/$mailboxId/inbox/labels/$label/email/$emailId'
      path: '/inbox/labels/$label/email/$emailId'
      fullPath: '/$mailboxId/inbox/labels/$label/email/$emailId'
      preLoaderRoute: typeof DashboardMailboxIdInboxLabelsLabelEmailEmailIdRouteImport
      parentRoute: typeof DashboardMailboxIdRouteRoute
    }
  }
}

interface DashboardMailboxIdSettingsRouteRouteChildren {
  DashboardMailboxIdSettingsAccountRoute: typeof DashboardMailboxIdSettingsAccountRoute
  DashboardMailboxIdSettingsAiRoute: typeof DashboardMailboxIdSettingsAiRoute
  DashboardMailboxIdSettingsAppearanceRoute: typeof DashboardMailboxIdSettingsAppearanceRoute
  DashboardMailboxIdSettingsDangerRoute: typeof DashboardMailboxIdSettingsDangerRoute
  DashboardMailboxIdSettingsLabelsRoute: typeof DashboardMailboxIdSettingsLabelsRoute
  DashboardMailboxIdSettingsMailboxRoute: typeof DashboardMailboxIdSettingsMailboxRoute
  DashboardMailboxIdSettingsPerformanceRoute: typeof DashboardMailboxIdSettingsPerformanceRoute
  DashboardMailboxIdSettingsSignaturesRoute: typeof DashboardMailboxIdSettingsSignaturesRoute
  DashboardMailboxIdSettingsTemplatesRoute: typeof DashboardMailboxIdSettingsTemplatesRoute
  DashboardMailboxIdSettingsIndexRoute: typeof DashboardMailboxIdSettingsIndexRoute
}

const DashboardMailboxIdSettingsRouteRouteChildren: DashboardMailboxIdSettingsRouteRouteChildren =
  {
    DashboardMailboxIdSettingsAccountRoute:
      DashboardMailboxIdSettingsAccountRoute,
    DashboardMailboxIdSettingsAiRoute: DashboardMailboxIdSettingsAiRoute,
    DashboardMailboxIdSettingsAppearanceRoute:
      DashboardMailboxIdSettingsAppearanceRoute,
    DashboardMailboxIdSettingsDangerRoute:
      DashboardMailboxIdSettingsDangerRoute,
    DashboardMailboxIdSettingsLabelsRoute:
      DashboardMailboxIdSettingsLabelsRoute,
    DashboardMailboxIdSettingsMailboxRoute:
      DashboardMailboxIdSettingsMailboxRoute,
    DashboardMailboxIdSettingsPerformanceRoute:
      DashboardMailboxIdSettingsPerformanceRoute,
    DashboardMailboxIdSettingsSignaturesRoute:
      DashboardMailboxIdSettingsSignaturesRoute,
    DashboardMailboxIdSettingsTemplatesRoute:
      DashboardMailboxIdSettingsTemplatesRoute,
    DashboardMailboxIdSettingsIndexRoute: DashboardMailboxIdSettingsIndexRoute,
  }

const DashboardMailboxIdSettingsRouteRouteWithChildren =
  DashboardMailboxIdSettingsRouteRoute._addFileChildren(
    DashboardMailboxIdSettingsRouteRouteChildren,
  )

interface DashboardMailboxIdRouteRouteChildren {
  DashboardMailboxIdSettingsRouteRoute: typeof DashboardMailboxIdSettingsRouteRouteWithChildren
  DashboardMailboxIdScreenerRoute: typeof DashboardMailboxIdScreenerRoute
  DashboardMailboxIdSubscriptionsRoute: typeof DashboardMailboxIdSubscriptionsRoute
  DashboardMailboxIdIndexRoute: typeof DashboardMailboxIdIndexRoute
  DashboardMailboxIdInboxDraftsRoute: typeof DashboardMailboxIdInboxDraftsRoute
  DashboardMailboxIdInboxSearchRoute: typeof DashboardMailboxIdInboxSearchRoute
  DashboardMailboxIdFolderIndexRoute: typeof DashboardMailboxIdFolderIndexRoute
  DashboardMailboxIdInboxIndexRoute: typeof DashboardMailboxIdInboxIndexRoute
  DashboardMailboxIdFolderEmailEmailIdRoute: typeof DashboardMailboxIdFolderEmailEmailIdRoute
  DashboardMailboxIdInboxEmailEmailIdRoute: typeof DashboardMailboxIdInboxEmailEmailIdRoute
  DashboardMailboxIdViewsViewIdIndexRoute: typeof DashboardMailboxIdViewsViewIdIndexRoute
  DashboardMailboxIdInboxLabelsLabelIndexRoute: typeof DashboardMailboxIdInboxLabelsLabelIndexRoute
  DashboardMailboxIdInboxLabelsLabelEmailEmailIdRoute: typeof DashboardMailboxIdInboxLabelsLabelEmailEmailIdRoute
}

const DashboardMailboxIdRouteRouteChildren: DashboardMailboxIdRouteRouteChildren =
  {
    DashboardMailboxIdSettingsRouteRoute:
      DashboardMailboxIdSettingsRouteRouteWithChildren,
    DashboardMailboxIdScreenerRoute: DashboardMailboxIdScreenerRoute,
    DashboardMailboxIdSubscriptionsRoute: DashboardMailboxIdSubscriptionsRoute,
    DashboardMailboxIdIndexRoute: DashboardMailboxIdIndexRoute,
    DashboardMailboxIdInboxDraftsRoute: DashboardMailboxIdInboxDraftsRoute,
    DashboardMailboxIdInboxSearchRoute: DashboardMailboxIdInboxSearchRoute,
    DashboardMailboxIdFolderIndexRoute: DashboardMailboxIdFolderIndexRoute,
    DashboardMailboxIdInboxIndexRoute: DashboardMailboxIdInboxIndexRoute,
    DashboardMailboxIdFolderEmailEmailIdRoute:
      DashboardMailboxIdFolderEmailEmailIdRoute,
    DashboardMailboxIdInboxEmailEmailIdRoute:
      DashboardMailboxIdInboxEmailEmailIdRoute,
    DashboardMailboxIdViewsViewIdIndexRoute:
      DashboardMailboxIdViewsViewIdIndexRoute,
    DashboardMailboxIdInboxLabelsLabelIndexRoute:
      DashboardMailboxIdInboxLabelsLabelIndexRoute,
    DashboardMailboxIdInboxLabelsLabelEmailEmailIdRoute:
      DashboardMailboxIdInboxLabelsLabelEmailEmailIdRoute,
  }

const DashboardMailboxIdRouteRouteWithChildren =
  DashboardMailboxIdRouteRoute._addFileChildren(
    DashboardMailboxIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardMailboxIdRouteRoute: typeof DashboardMailboxIdRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMailboxIdRouteRoute: DashboardMailboxIdRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EmailMailboxIdEmailIdRoute: EmailMailboxIdEmailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
