/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as DashboardTasksRouteImport } from './routes/_dashboard/tasks'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard/home'
import { Route as DashboardGetStartedRouteImport } from './routes/_dashboard/get-started'
import { Route as DashboardNotesIndexRouteImport } from './routes/_dashboard/notes/index'
import { Route as DashboardNotesNoteIdRouteImport } from './routes/_dashboard/notes/$noteId'
import { Route as DashboardInboxIdIndexRouteImport } from './routes/_dashboard/inbox/$id/index'
import { Route as DashboardInboxIdSubscriptionsRouteImport } from './routes/_dashboard/inbox/$id/subscriptions'
import { Route as DashboardInboxIdFiltersRouteImport } from './routes/_dashboard/inbox/$id/filters'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGetStartedRoute = DashboardGetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotesIndexRoute = DashboardNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotesNoteIdRoute = DashboardNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInboxIdIndexRoute = DashboardInboxIdIndexRouteImport.update({
  id: '/inbox/$id/',
  path: '/inbox/$id/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInboxIdSubscriptionsRoute =
  DashboardInboxIdSubscriptionsRouteImport.update({
    id: '/inbox/$id/subscriptions',
    path: '/inbox/$id/subscriptions',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInboxIdFiltersRoute = DashboardInboxIdFiltersRouteImport.update({
  id: '/inbox/$id/filters',
  path: '/inbox/$id/filters',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/get-started': typeof DashboardGetStartedRoute
  '/home': typeof DashboardHomeRoute
  '/settings': typeof DashboardSettingsRoute
  '/tasks': typeof DashboardTasksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/notes/$noteId': typeof DashboardNotesNoteIdRoute
  '/notes/': typeof DashboardNotesIndexRoute
  '/inbox/$id/filters': typeof DashboardInboxIdFiltersRoute
  '/inbox/$id/subscriptions': typeof DashboardInboxIdSubscriptionsRoute
  '/inbox/$id/': typeof DashboardInboxIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/get-started': typeof DashboardGetStartedRoute
  '/home': typeof DashboardHomeRoute
  '/settings': typeof DashboardSettingsRoute
  '/tasks': typeof DashboardTasksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs': typeof DocsIndexRoute
  '/notes/$noteId': typeof DashboardNotesNoteIdRoute
  '/notes': typeof DashboardNotesIndexRoute
  '/inbox/$id/filters': typeof DashboardInboxIdFiltersRoute
  '/inbox/$id/subscriptions': typeof DashboardInboxIdSubscriptionsRoute
  '/inbox/$id': typeof DashboardInboxIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/get-started': typeof DashboardGetStartedRoute
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/tasks': typeof DashboardTasksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/_dashboard/notes/$noteId': typeof DashboardNotesNoteIdRoute
  '/_dashboard/notes/': typeof DashboardNotesIndexRoute
  '/_dashboard/inbox/$id/filters': typeof DashboardInboxIdFiltersRoute
  '/_dashboard/inbox/$id/subscriptions': typeof DashboardInboxIdSubscriptionsRoute
  '/_dashboard/inbox/$id/': typeof DashboardInboxIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/get-started'
    | '/home'
    | '/settings'
    | '/tasks'
    | '/docs/$slug'
    | '/docs/'
    | '/notes/$noteId'
    | '/notes/'
    | '/inbox/$id/filters'
    | '/inbox/$id/subscriptions'
    | '/inbox/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/get-started'
    | '/home'
    | '/settings'
    | '/tasks'
    | '/docs/$slug'
    | '/docs'
    | '/notes/$noteId'
    | '/notes'
    | '/inbox/$id/filters'
    | '/inbox/$id/subscriptions'
    | '/inbox/$id'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/docs'
    | '/login'
    | '/_dashboard/get-started'
    | '/_dashboard/home'
    | '/_dashboard/settings'
    | '/_dashboard/tasks'
    | '/docs/$slug'
    | '/docs/'
    | '/_dashboard/notes/$noteId'
    | '/_dashboard/notes/'
    | '/_dashboard/inbox/$id/filters'
    | '/_dashboard/inbox/$id/subscriptions'
    | '/_dashboard/inbox/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_dashboard/tasks': {
      id: '/_dashboard/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/get-started': {
      id: '/_dashboard/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof DashboardGetStartedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/notes/': {
      id: '/_dashboard/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof DashboardNotesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/notes/$noteId': {
      id: '/_dashboard/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof DashboardNotesNoteIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/inbox/$id/': {
      id: '/_dashboard/inbox/$id/'
      path: '/inbox/$id'
      fullPath: '/inbox/$id/'
      preLoaderRoute: typeof DashboardInboxIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/inbox/$id/subscriptions': {
      id: '/_dashboard/inbox/$id/subscriptions'
      path: '/inbox/$id/subscriptions'
      fullPath: '/inbox/$id/subscriptions'
      preLoaderRoute: typeof DashboardInboxIdSubscriptionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/inbox/$id/filters': {
      id: '/_dashboard/inbox/$id/filters'
      path: '/inbox/$id/filters'
      fullPath: '/inbox/$id/filters'
      preLoaderRoute: typeof DashboardInboxIdFiltersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardGetStartedRoute: typeof DashboardGetStartedRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardNotesNoteIdRoute: typeof DashboardNotesNoteIdRoute
  DashboardNotesIndexRoute: typeof DashboardNotesIndexRoute
  DashboardInboxIdFiltersRoute: typeof DashboardInboxIdFiltersRoute
  DashboardInboxIdSubscriptionsRoute: typeof DashboardInboxIdSubscriptionsRoute
  DashboardInboxIdIndexRoute: typeof DashboardInboxIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardGetStartedRoute: DashboardGetStartedRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardNotesNoteIdRoute: DashboardNotesNoteIdRoute,
  DashboardNotesIndexRoute: DashboardNotesIndexRoute,
  DashboardInboxIdFiltersRoute: DashboardInboxIdFiltersRoute,
  DashboardInboxIdSubscriptionsRoute: DashboardInboxIdSubscriptionsRoute,
  DashboardInboxIdIndexRoute: DashboardInboxIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
